- hosts: 'local'
  gather_facts: no
  roles:
    - beginning
    - homebrew-tap
    - homebrew
    - homebrew-cask
    - mas
    - ending

  vars:
    homebrew_repositories:
      - caskroom/cask
      - caskroom/versions

    homebrew_packages:
      - { name: ansible }
      - { name: carthage }
      - { name: gdbm }
      - { name: git }
      - { name: git-flow }
      - { name: libevent }
      - { name: libyaml }
      - { name: mas }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: pkg-config }
      - { name: python }
      - { name: readline }
      - { name: sqlite }
      - { name: tmux }
      - { name: zsh }

    homebrew_cask_packages:
      - { name: atom }
      - { name: avast-security }
      - { name: docker }
      - { name: dropbox }
      - { name: evernote }
      - { name: firefox }
      - { name: geektool}
      - { name: google-chrome }
      - { name: istat-menus5 }
      - { name: iterm2 }
      - { name: java }
      - { name: java6 }
      - { name: java8 }
      - { name: intellij-idea }
      - { name: karabiner-elements }
      - { name: kindle }
      - { name: slack }
      - { name: spotify }
      - { name: 5kplayer }

    mas_applications:
      - { id: 497799835, name: Xcode }
      - { id: 539883307, name: LINE }
      - { id: 585829637, name: Todoist }
      - { id: 634148309, name: LogicProX }
      - { id: 1007457278, name: Realm Browser }
      - { id: 1176895641, name: Spark }
