---
- name: install homebrew cask packages
  homebrew_cask:
    name: '{{ item.name }}'
    state: installed
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: '{{ homebrew_cask_packages }}'
