---

- name: Install Homebrew Cask Packages
  homebrew_cask:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    install_options: 'appdir=/Applications'
    greedy: true
  with_items: '{{ homebrew_cask_packages }}'
  tags: homebrew-cask-install
